{{ $namespace := .Values.namespace }}
{{- range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-service.name" $ }}-{{ .name }}
  labels:
    {{- include "generic-service.labels" $ | nindent 4 }}
  namespace: {{ $namespace }}
type: Opaque
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
